### ISSUE TITLE
Showcase integration of PayPal JS

### ISSUE THREAD

**Issue by shrutikapoor08** [paypal-examples/js-sdk-standard-integration#1]
Have you integrated with PayPal JS? We want to see your integration samples. 
Add examples of PayPal JS integration to this repository. 

Sample integration: https://github.com/paypal-examples/js-sdk-standard-integration
GitHub repo: https://github.com/paypal/paypal-js

**Comment by M-krishna** [comment]
@shrutikapoor08 Do I need to create a new examples folder?

**Comment by BhautikChudasama** [comment]
Added React Hooks + Paypal integration example #3

**Comment by mstuart** [comment]
Thanks @M-krishna @BhautikChudasama !

**Comment by BhautikChudasama** [comment]
How we can merge pool requests? 😊 @mstuart @shrutikapoor08

**Comment by shrutikapoor08** [comment]
Thank you for your contributions @BhautikChudasama and @M-krishna. I have added hacktoberfest-accepted label so you can get credit for your contributions. We are doing an internal review and will merge the PRs afterwards.

**Comment by ng29** [comment]
Hey @shrutikapoor08 

Are more integrations acceptable, incase i wanna give it a shot :)

Cheers

**Comment by M-krishna** [comment]
> Thank you for your contributions @BhautikChudasama and @M-krishna. I have added hacktoberfest-accepted label so you can get credit for your contributions. We are doing an internal review and will merge the PRs afterwards.

Hey @shrutikapoor08  , Is there any update on this [PR](https://github.com/paypal-examples/js-sdk-standard-integration/pull/2).

And also are we getting any [Prices](https://github.com/shrutikapoor08/hacktoberfest-2#prizes) 😀 ?

**Comment by codewith-arijit** [comment]
Hi, Can I be assigned this issue for this year's hacktoberfest 2021?

**Comment by manavmodi22** [comment]
Is the issue still open for contribution?

**Comment by jayprakash02** [comment]
Hello @shrutikapoor08, Is this issue is still open for hacktoberfest 2021

**Comment by mstuart** [comment]
Hi everyone, this one was worked on by @BhautikChudasama and @M-krishna last year, then I saw that @codewith-arijit just sent up a PR w/ a Django example. This Issue should have been marked closed last year, but it was still lingering out there. Our mistake. Sorry! @codewith-arijit, you'll get credit for your Django contribution though. Thanks!
